# This workflow will do a clean installation of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [18.x, 20.x, 22.x]
    #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # Checkout code from repo
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Setup NodeJS
      # - name: Use Node.js ${{ matrix.node-version }}
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # cache: 'npm'

      # Install fresh dependencies
      - name: Install dependencies
        run: npm ci

      # Build project
      - name: Build project
        run: npm run build --if-present

      # Deploy to github pages
      - name: Deploy built files
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
